version: '3.8'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    restart: unless-stopped
    networks:
      - visionbones
    volumes:
      - ./logs/webapp:/app/logs

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBAPP_URL=${TELEGRAM_WEBAPP_URL}
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - webapp
    networks:
      - visionbones
    volumes:
      - ./logs/bot:/app/logs

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - webapp
    restart: unless-stopped
    networks:
      - visionbones

  # PM2 Web Monitoring (optional)
  pm2-web:
    image: keymetrics/pm2:latest-alpine
    container_name: pm2-web
    restart: unless-stopped
    ports:
      - "9615:9615"
    environment:
      - PM2_WEB_USER=admin
      - PM2_WEB_PASSWORD=${PM2_WEB_PASSWORD:-visionbones2024}
    networks:
      - visionbones
    profiles:
      - monitoring

networks:
  visionbones:
    driver: bridge

volumes:
  webapp_logs:
  bot_logs:
  nginx_logs: