version: '3.8'

services:
  webapp-dev:
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    volumes:
      - ./webapp/src:/app/src
      - ./webapp/public:/app/public
      - ./webapp/index.html:/app/index.html
      - ./webapp/vite.config.ts:/app/vite.config.ts
    restart: unless-stopped
    networks:
      - visionbones

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBAPP_URL=http://localhost:3000
    restart: unless-stopped
    depends_on:
      - webapp-dev
    networks:
      - visionbones

networks:
  visionbones:
    driver: bridge